#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_DISTRO=armbian
BASE_ROOT_PARTITION=2
BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=8192
BASE_IMAGE_RESIZEROOT=600
BASE_IMAGE_RASPBIAN=no
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
DOWNLOAD_URL_IMAGE="https://dl.armbian.com/bigtreetech-cb1/archive/Armbian_24.2.2_Bigtreetech-cb1_jammy_current_6.6.17.img.xz"

# Custom
RATOS_CONFIGURATOR_SHIP=https://github.com/asychev/RatOS-configurator.git
RATOS_CONFIGURATOR_BRANCH=v2.x-deployment-cb1

RATOS_CONFIG_SHIP=https://github.com/asychev/RatOS-configuration.git
RATOS_CONFIG_BRANCH=v2.x-manta-m4p-2.2

# export Variables
export BASE_DISTRO
export BASE_ROOT_PARTITION
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_IMAGE_RASPBIAN
export BASE_ADD_USER
export BASE_USER
export BASE_USER_PASSWORD
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export RATOS_CONFIGURATOR_SHIP
export RATOS_CONFIGURATOR_BRANCH
export RATOS_CONFIG_SHIP
export RATOS_CONFIG_BRANCH

export MODULES="base,cb1cleanup,passwordless_sudo(cb1config,pkgupgrade(network,cb1spi,klipper,node,is_req_preinstall,moonraker,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot),dfu-util)))"
