#!/usr/bin/env bash
#### CB1CLEANUP - Clean up source CB1 image module

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Cleaning up source CB1 image..."

apt purge network-manager isc-dhcp-client -y
apt autoremove -y

rm -rf /boot/gcode
rm -rf /boot/scripts
echo "" > /etc/rc.local

userdel -r -f biqu
sed -i '/%biqu ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers

rm -rf /etc/udev/rules.d/60-gpiod.rules

rm -rf /boot/system.cfg

echo_green "Cleaning up source CB1 image... DONE."
