#!/usr/bin/env bash
# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## Remove passwdless sudo
sed -i '/'"${BASE_USER}"' ALL=(ALL) NOPASSWD:ALL/d' /etc/sudoers
## END
