#!/usr/bin/env bash
# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

# passwordless sudo during install
# Will be removed in cleanup
echo "${BASE_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
